#ifndef CONFIG_H
#define CONFIG_H


#define SPEEDO // comment out if not using speedo.
#ifdef SPEEDO
//Speedo output
#define SPEED_OUTPUT_PIN 16
#define SPEED_OUTPUT_MIN_ANGLE 0
#define SPEED_OUTPUT_MAX_ANGLE 270
#define SPEED_OUTPUT_MIN_VALUE 0
#define SPEED_OUTPUT_MAX_VALUE 121
#define SPEED_OUTPUT_ISDIGITAL true
#define SPEED_OUTPUT_CLOCKWISE false

#define SPEED_SENSOR_PIN 27
#define PULSES_PER_MILE 13782
#define TIME_CONVERSION_FACTOR 3600.0
#define FEET_PER_MILE 5280.0

#endif


#define TACHO
#ifdef TACHO

#define TACHO_OUTPUT_PIN 19
#define TACHO_OUTPUT_MIN_ANGLE 0
#define TACHO_OUTPUT_MAX_ANGLE 270
#define TACHO_OUTPUT_MIN_VALUE 0
#define TACHO_OUTPUT_MAX_VALUE 6200
#define TACHO_OUTPUT_ISDIGITAL true
#define TACHO_OUTPUT_CLOCKWISE false

#define TACHO_SENSOR_PIN 26
#define PPR 2

#endif


#define OIL_PRESSURE_GAUGE
#ifdef OIL_PRESSURE_GAUGE

#define OIL_PRESSURE_GAUGE_PIN 5
#define OIL_PRESSURE_SENSOR_PIN 33
#define OIL_PRESSURE_MIN_READING 0
#define OIL_PRESSURE_MAX_READING 180
#define OIL_PRESSURE_MIN_VALUE 0
#define OIL_PRESSURE_MAX_VALUE 80
#define OIL_PRESSURE_IS_DIGITAL false
#define OIL_PRESSURE_CLOCKWISE true
#define OIL_PRESSURE_WARNING_THRESHOLD 15

#endif

#define BATTERY_CHARGE_GAUGE
#ifdef BATTERY_CHARGE_GAUGE

#define BATTERY_GAUGE_PIN 18
#define BATTERY_SENSOR_PIN 35
#define MIN_BATTERY_READING 1950
#define MAX_BATTERY_READING 2990
#define MIN_BATTERY_VALUE 0
#define MAX_BATTERY_VALUE 100
#define BATTERY_SENSOR_IS_DIGITAL false
#define BATTERY_LEVEL_CLOCKWISE true

#endif

#define FUEL_LEVEL_GAUGE
#ifdef FUEL_LEVEL_GAUGE

#define FUEL_LEVEL_GAUGE_PIN 17
#define FUEL_LEVEL_SENSOR_PIN 34
#define FUEL_LEVEL_MIN_READING 0
#define FUEL_LEVEL_MAX_READING 4096
#define FUEL_LEVEL_MIN_VALUE 0
#define FUEL_LEVEL_MAX_VALUE 100
#define FUEL_SENSOR_IS_DIGITAL false
#define FUEL_LEVEL_CLOCKWISE true


#endif

#define TEMP_LEVEL_GAUGE
#ifdef TEMP_LEVEL_GAUGE

#define TEMP_LEVEL_GAUGE_PIN 4
#define TEMP_LEVEL_SENSOR_PIN 32
#define TEMP_LEVEL_MIN_READING 0
#define TEMP_LEVEL_MAX_READING 4096
#define TEMP_LEVEL_MIN_VALUE 0
#define TEMP_LEVEL_MAX_VALUE 100
#define TEMP_SENSOR_IS_DIGITAL false
#define TEMP_LEVEL_CLOCKWISE true


#endif

#define STORAGE
#ifdef STORAGE 
    // EEPROM STORAGE
    #define EEPROMSTORAGE
    #ifdef EEPROMSTORAGE
        #define EEPROM_ADDRESS 0x50
        #define EEPROM_SIZE 256
    #endif

    //SD STORATE
    //#define SDSTORAGE
    #ifdef SDSTORAGE


    #endif


    #if defined(EEPROMSTORAGE) && defined(SDSTORAGE)
        #error "EEPROMSTORAGE and SDSTORAGE cannot coexist!"
    #endif

    #define LOGGING

#endif


#define ODOMETER

#define PANELLIGHTS

#ifdef PANELLIGHTS
#define OIL_LED_PIN 6
#define IGN_LED_PIN 7
#endif



#endif
